### ISSUE TITLE
Compatibility issue with NodeBB 1.14.x

### ISSUE THREAD

**Issue by Brutus5000** [NicolasSiver/nodebb-plugin-ns-embed#26]
## Case A: Fresh install of NodeBB 1.14

The search only offers version 2.1.1 and it's broken. There is no way to add the embed services.

## Case B: Upgrading from NodeBB 1.13

So I updated an existing 1.13.2 (with the plugin installed and working in version 4.0.0) to 1.14.2 and now I sort of lost the plugin in the upgrade process and if I'm reinstalling it I only get plugin version 2.1.1 with an upgrade button to 4.0.0.
But if I click on that I get this error message:

> Your version of NodeBB (v1.14.2) is only cleared to upgrade to v2.1.1 of this plugin. Please update your NodeBB if you wish to install a newer version of this plugin.

In the admin panel search I can still search for embed, and it finds the plugin page, but the page is gone if I click on it.

**Comment by Brutus5000** [comment]
So I manually installed version 4.0.0 on NobeBB 1.14.2 via npm on console and in general it's working (but Twitch setup seems to be broken now). Example post [here](https://forum.test.faforever.com/topic/4/hello-stonehenge/3)

**Comment by Brutus5000** [comment]
Now tested with NodeBB 1.14.3 and still all fine.

**Comment by gramakri** [comment]
I hit this as well in NodeBB 1.15. Let me try to install 4.0.0 manually. @Brutus5000 Do you know why it's not offered in ACP?

```
Nov 11 12:48:16 2020-11-11T20:48:16.957Z [4567/14304] - error: Error: Cannot find module './src/emitter'
Nov 11 12:48:16 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Nov 11 12:48:16 at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Nov 11 12:48:16 at Module.require (internal/modules/cjs/loader.js:692:17)
Nov 11 12:48:16 at require (internal/modules/cjs/helpers.js:25:18)
Nov 11 12:48:16 at Module.require.main.require (/app/code/require-main.js:8:10)
Nov 11 12:48:16 at /run/nodebb/node_modules/nodebb-plugin-ns-embed/plugin/nodebb.js:8:31
Nov 11 12:48:16 at Object.<anonymous> (/run/nodebb/node_modules/nodebb-plugin-ns-embed/plugin/nodebb.js:44:3)
Nov 11 12:48:16 at Module._compile (internal/modules/cjs/loader.js:778:30)
Nov 11 12:48:16 at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Nov 11 12:48:16 at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by Brutus5000** [comment]
@gramakri This is due to the compatiblity settings in the package json.
Current version declares it only compatible to 1.13 branch [link](https://github.com/NicolasSiver/nodebb-plugin-ns-embed/blob/master/package.json#L45)
If you look at older tags it was declared for the whole 1.x release familiy upwards [link](https://github.com/NicolasSiver/nodebb-plugin-ns-embed/blob/v2.1.1/package.json)

The ACP compares it with your version and only offer you version that are supposed to be compatible.

**Comment by gramakri** [comment]
Can confirm that manually installing using npm works. Thanks @Brutus5000

**Comment by NicolasSiver** [comment]
There will be a new release with NodeBB 17 compatibility.
