### ISSUE TITLE
Compatibility with 1.12.x?

### ISSUE THREAD

**Issue by bdharrington7** [NicolasSiver/nodebb-plugin-ns-embed#18]
it's stopped parsing when I upgraded from 1.10.x to 1.12.x. In the package.json the semver range is `~1.11.0`

**Comment by PatheticMustan** [comment]
```
2019-05-31T00:26:08.870Z [4567/22684] - [31merror[39m: Error: Cannot find module './src/emitter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Module.require.main.require (/root/nodebb/require-main.js:8:10)
    at /root/nodebb/node_modules/nodebb-plugin-ns-embed/plugin/nodebb.js:8:31
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-ns-embed/plugin/nodebb.js:44:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
2019-05-31T00:26:08.870Z [4567/22684] - [33mwarn[39m: [plugins] Unable to parse library for: nodebb-plugin-ns-embed
```
I too, have this problem.

It also says the dependencies are out of date.

Currently on 1.12.2. :P

**Comment by NicolasSiver** [comment]
@PatheticMustan you are using an older version of the plugin.  Is it v3?

**Comment by PatheticMustan** [comment]
Not sure. Just installed it from nbbpm today ;(

**Comment by PatheticMustan** [comment]
Version 2.1.1

**Comment by PatheticMustan** [comment]
The nodebb package manager says 2.1.1!
![image](https://user-images.githubusercontent.com/35382971/58674024-fb00cc80-831b-11e9-97f8-d367292cf2ca.png)
hmm
very dr. strange

**Comment by bdharrington7** [comment]
Yeah 2.1.1 only shows up because of the nbb compatibility semver range in the package.json:
https://github.com/NicolasSiver/nodebb-plugin-ns-embed/blob/master/package.json#L45

**Comment by openbullet** [comment]
I just cloned the repo (v3.0.1) to node_modules, activated the plugin and it's not showing up in the plugins dropdown menu (to setup the rules). Yes I did reload and rebuild NodeBB. Anyone knows how I can fix this please? Thanks.

**Comment by NicolasSiver** [comment]
Did you clone and install plugin dependencies?

**Comment by openbullet** [comment]
I deleted the previously created folder that I cloned and tried again like this
```
./nodebb stop
npm install https://github.com/NicolasSiver/nodebb-plugin-ns-embed
./nodebb upgrade
./nodebb start
```
I figured npm should take care of the dependencies. It still does not work. I performed the same procedure for your other plugin ns-awards and it works perfectly.

**Comment by openbullet** [comment]
@NicolasSiver Hey, today I added a totally unrelated plugin and the `Embed` voice appeared in the menu too! Very weird but it worked ^_^ I genuinely don't know what black magic happened there.

**Comment by PatheticMustan** [comment]
@openbullet, what's this magical plugin? tell us your secretssssss

**Comment by openbullet** [comment]
@PatheticMustan you need to do exactly as I did though, don't install directly from nodeBB's plugin system because it's an old version. Use the commands I posted yesterday to install with npm. Then I installed the 
poll plugin to create polls and restarted nodeBB from the admin panel. All works now :D

**Comment by NicolasSiver** [comment]
You could try something like this:

```shell
# Visit NodeBB directory
npm install nodebb-plugin-ns-embed
cd ./node_modules/nodebb-plugin-ns-embed
npm install
cd ../../
./nodebb build
./nodebb start
```

**Comment by PatheticMustan** [comment]
@openbullet's commands worked!
Could the nodebb package manager be updated to the right version?

**Comment by PatheticMustan** [comment]
Look, an example!
https://cpos.ml/topic/308/embeds-work-omg/2
;)

**Comment by bdharrington7** [comment]
https://github.com/NicolasSiver/nodebb-plugin-ns-embed/pull/19

**Comment by NicolasSiver** [comment]
The plugin should be compatible with the latest NodeBB 1.13
